/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauces.agenciaalquiler.vista;

/**
 *
 * @author daw1
 */
public class DialogoVehiculo extends javax.swing.JDialog  {

    /**
     * Creates new form DialogoVehiculo
     */
    public DialogoVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dPDatos = new javax.swing.JPanel();
        dLMatricula = new javax.swing.JLabel();
        dLGrupo = new javax.swing.JLabel();
        dLTipo = new javax.swing.JLabel();
        dLPlazas = new javax.swing.JLabel();
        dLCapacidad = new javax.swing.JLabel();
        dBAceptar = new javax.swing.JButton();
        dBCancelar = new javax.swing.JButton();
        dTMatricula = new javax.swing.JTextField();
        dTGrupo = new javax.swing.JComboBox<>();
        dTTipo = new javax.swing.JComboBox<>();
        dTPlazas = new javax.swing.JSpinner();
        dTCapacidad = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dPDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de vehículo"));

        dLMatricula.setText("MATRÍCULA");

        dLGrupo.setText("GRUPO");

        dLTipo.setText("TIPO");

        dLPlazas.setText("PLAZAS");

        dLCapacidad.setText("CAPACIDAD");
        dLCapacidad.setVisible(false);

        dBAceptar.setText("ACEPTAR");
        dBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBAceptarActionPerformed(evt);
            }
        });

        dBCancelar.setText("CANCELAR");
        dBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBCancelarActionPerformed(evt);
            }
        });

        dTGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        dTTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURISMO", "FURGONETA" }));
        dTTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dTTipoItemStateChanged(evt);
            }
        });

        dTCapacidad.setVisible(false);

        javax.swing.GroupLayout dPDatosLayout = new javax.swing.GroupLayout(dPDatos);
        dPDatos.setLayout(dPDatosLayout);
        dPDatosLayout.setHorizontalGroup(
            dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dPDatosLayout.createSequentialGroup()
                        .addComponent(dLMatricula)
                        .addGap(30, 30, 30)
                        .addComponent(dTMatricula))
                    .addGroup(dPDatosLayout.createSequentialGroup()
                        .addGroup(dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dPDatosLayout.createSequentialGroup()
                                .addComponent(dLGrupo)
                                .addGap(18, 18, 18)
                                .addComponent(dTGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dPDatosLayout.createSequentialGroup()
                                .addComponent(dLPlazas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dTPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dPDatosLayout.createSequentialGroup()
                                .addComponent(dLCapacidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dTCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dPDatosLayout.createSequentialGroup()
                                .addComponent(dLTipo)
                                .addGap(18, 18, 18)
                                .addComponent(dTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(dPDatosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(dBAceptar)
                        .addGap(63, 63, 63)
                        .addComponent(dBCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dPDatosLayout.setVerticalGroup(
            dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPDatosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLMatricula)
                    .addComponent(dTMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLGrupo)
                    .addComponent(dLTipo)
                    .addComponent(dTGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dTTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dLPlazas)
                    .addComponent(dTPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dTCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dLCapacidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(dPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dBAceptar)
                    .addComponent(dBCancelar))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dPDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dTTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dTTipoItemStateChanged
        if (getTipo().equals("TURISMO")){
            dLCapacidad.setVisible(false);
            dTCapacidad.setVisible(false);
            dLPlazas.setVisible(true);
            dTPlazas.setVisible(true);
        }
        else{
            dLCapacidad.setVisible(true);
            dTCapacidad.setVisible(true);
            dLPlazas.setVisible(false);
            dTPlazas.setVisible(false);
        }
    }//GEN-LAST:event_dTTipoItemStateChanged

    private void dBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBAceptarActionPerformed
        opcion=ACEPTAR;
        setVisible(false);
    }//GEN-LAST:event_dBAceptarActionPerformed

    private void dBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBCancelarActionPerformed
        opcion=CANCELAR;
        setVisible(false);
    }//GEN-LAST:event_dBCancelarActionPerformed
    
    public String getMatricula(){
        return this.dTMatricula.getText();
    }
    
    public String getGrupo(){
        return (String)this.dTGrupo.getSelectedItem();
    }
    
    public String getTipo(){
        return (String)this.dTTipo.getSelectedItem();
    }
    
    public int getPlazas(){
        return (int)this.dTPlazas.getValue();
    }
    
    public float getCapacidad(){
        return Float.parseFloat(this.dTCapacidad.getText());
    }
    
    public int mostrar(){
        limpiarCampos();
        opcion=CANCELAR;
        setVisible(true);
        
        return opcion;
    }
    
    public void limpiarCampos(){
        this.dTMatricula.setText("");
        this.dTPlazas.setValue(0);
        this.dTCapacidad.setText("");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogoVehiculo(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    private int opcion;
    public static final int ACEPTAR=1;
    public static final int CANCELAR=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dBAceptar;
    private javax.swing.JButton dBCancelar;
    private javax.swing.JLabel dLCapacidad;
    private javax.swing.JLabel dLGrupo;
    private javax.swing.JLabel dLMatricula;
    private javax.swing.JLabel dLPlazas;
    private javax.swing.JLabel dLTipo;
    private javax.swing.JPanel dPDatos;
    private javax.swing.JFormattedTextField dTCapacidad;
    private javax.swing.JComboBox<String> dTGrupo;
    private javax.swing.JTextField dTMatricula;
    private javax.swing.JSpinner dTPlazas;
    private javax.swing.JComboBox<String> dTTipo;
    // End of variables declaration//GEN-END:variables
}
