/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sauces.agenciaalquiler.vista;

import com.sauces.agenciaalquiler.controlador.Controlador;
import com.sauces.agenciaalquiler.modelo.MatriculaException;
import com.sauces.agenciaalquiler.modelo.Vehiculo;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author daw1
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        selectorFicheros = new javax.swing.JFileChooser();
        pDatos = new javax.swing.JPanel();
        lMatricula = new javax.swing.JLabel();
        lGrupo = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        lPlazas = new javax.swing.JLabel();
        lPrecioDia = new javax.swing.JLabel();
        pOperaciones = new javax.swing.JPanel();
        bBarato = new javax.swing.JButton();
        bCaro = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMatricula = new javax.swing.JTextPane();
        tGrupo = new javax.swing.JComboBox<>();
        tTipo = new javax.swing.JComboBox<>();
        tPlazas = new javax.swing.JSpinner();
        lCapacidad = new javax.swing.JLabel();
        tCapacidad = new javax.swing.JFormattedTextField();
        tPrecio = new javax.swing.JFormattedTextField();
        pListado = new javax.swing.JPanel();
        bListar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        lOrden = new javax.swing.JLabel();
        lFGrupo = new javax.swing.JLabel();
        lFTipo = new javax.swing.JLabel();
        tFGrupo = new javax.swing.JComboBox<>();
        tFTipo = new javax.swing.JComboBox<>();
        rMatricula = new javax.swing.JRadioButton();
        rPrecio = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mArchivoAbrir = new javax.swing.JMenuItem();
        mArchivoGuardar = new javax.swing.JMenuItem();
        mVehiculo = new javax.swing.JMenu();
        mVehiculoNuevo = new javax.swing.JMenuItem();
        mVehiculoBuscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de vehículo"));

        lMatricula.setText("MATRÍCULA");

        lGrupo.setText("GRUPO");

        lTipo.setText("TIPO");

        lPlazas.setText("PLAZAS");

        lPrecioDia.setText("PRECIO POR DÍA");

        pOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Otras operaciones"));

        bBarato.setText("MOSTRAR VEHÍCULO MÁS BARATO");
        bBarato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaratoActionPerformed(evt);
            }
        });

        bCaro.setText("MOSTRAR VEHÍCULO MÁS CARO");
        bCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pOperacionesLayout = new javax.swing.GroupLayout(pOperaciones);
        pOperaciones.setLayout(pOperacionesLayout);
        pOperacionesLayout.setHorizontalGroup(
            pOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOperacionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBarato)
                    .addGroup(pOperacionesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bCaro)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pOperacionesLayout.setVerticalGroup(
            pOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOperacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bBarato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCaro)
                .addContainerGap())
        );

        bBorrar.setText("BORRAR");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        bModificar.setText("MODIFICAR");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tMatricula);

        tGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));

        tTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURISMO", "FURGONETA" }));

        lCapacidad.setText("CAPACIDAD");

        javax.swing.GroupLayout pDatosLayout = new javax.swing.GroupLayout(pDatos);
        pDatos.setLayout(pDatosLayout);
        pDatosLayout.setHorizontalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addComponent(lGrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lPrecioDia)
                                    .addComponent(lCapacidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tCapacidad)
                                    .addComponent(tPrecio)))))
                    .addGroup(pDatosLayout.createSequentialGroup()
                        .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(bBorrar)
                                .addGap(42, 42, 42)
                                .addComponent(bModificar))
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDatosLayout.createSequentialGroup()
                                        .addComponent(lMatricula)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pDatosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDatosLayout.createSequentialGroup()
                                        .addComponent(lPlazas)
                                        .addGap(18, 18, 18)
                                        .addComponent(tPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pDatosLayout.setVerticalGroup(
            pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMatricula)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lGrupo)
                    .addComponent(tGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTipo)
                    .addComponent(tTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPlazas)
                    .addComponent(tPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCapacidad)
                    .addComponent(tCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPrecioDia)
                    .addComponent(tPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar)
                    .addComponent(bModificar))
                .addGap(18, 18, 18)
                .addComponent(pOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pListado.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de vehículos"));

        bListar.setText("LISTAR VEHÍCULOS");
        bListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarActionPerformed(evt);
            }
        });

        vehiculoTM=new VehiculoTableModel();
        tablaVehiculos.setModel(vehiculoTM);
        tablaVehiculos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent lse){
                int fila=tablaVehiculos.getSelectedRow();
                if(fila>=0){
                    tMatricula.setText(tablaVehiculos.getValueAt(fila,0).toString());
                    tTipo.setSelectedItem(tablaVehiculos.getValueAt(fila,1));
                    tGrupo.setSelectedItem(tablaVehiculos.getValueAt(fila,2));
                    tPlazas.setValue(tablaVehiculos.getValueAt(fila, 3));
                    tCapacidad.setValue(tablaVehiculos.getValueAt(fila, 4));
                    tPrecio.setText(tablaVehiculos.getValueAt(fila, 5).toString());
                }
            }
        });
        jScrollPane3.setViewportView(tablaVehiculos);

        lOrden.setText("ORDEN DEL LISTADO");

        lFGrupo.setText("FILTRAR POR GRUPO");

        lFTipo.setText("FILTRAR POR TIPO");

        tFGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "A", "B", "C" }));

        tFTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURISMO", "FURGONETA" }));

        buttonGroup1.add(rMatricula);
        rMatricula.setSelected(true);
        rMatricula.setText("MATRÍCULA");

        buttonGroup1.add(rPrecio);
        rPrecio.setText("PRECIO ALQUILER");

        javax.swing.GroupLayout pListadoLayout = new javax.swing.GroupLayout(pListado);
        pListado.setLayout(pListadoLayout);
        pListadoLayout.setHorizontalGroup(
            pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pListadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bListar)
                .addGap(282, 282, 282))
            .addGroup(pListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pListadoLayout.createSequentialGroup()
                        .addComponent(lOrden)
                        .addGap(138, 138, 138)
                        .addComponent(lFGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tFGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lFTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tFTipo, 0, 107, Short.MAX_VALUE))
                    .addGroup(pListadoLayout.createSequentialGroup()
                        .addComponent(rMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rPrecio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pListadoLayout.setVerticalGroup(
            pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lOrden)
                    .addComponent(lFGrupo)
                    .addComponent(lFTipo)
                    .addComponent(tFGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rMatricula)
                    .addComponent(rPrecio))
                .addGap(29, 29, 29))
        );

        mArchivo.setText("Archivo");

        mArchivoAbrir.setText("Abrir...");
        mArchivoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mArchivoAbrirActionPerformed(evt);
            }
        });
        mArchivo.add(mArchivoAbrir);

        mArchivoGuardar.setText("Guardar...");
        mArchivoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mArchivoGuardarActionPerformed(evt);
            }
        });
        mArchivo.add(mArchivoGuardar);

        jMenuBar1.add(mArchivo);

        mVehiculo.setText("Vehículo");

        mVehiculoNuevo.setText("Nuevo...");
        mVehiculoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVehiculoNuevoActionPerformed(evt);
            }
        });
        mVehiculo.add(mVehiculoNuevo);

        mVehiculoBuscar.setText("Buscar...");
        mVehiculoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVehiculoBuscarActionPerformed(evt);
            }
        });
        mVehiculo.add(mVehiculoBuscar);

        jMenuBar1.add(mVehiculo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pListado, javax.swing.GroupLayout.PREFERRED_SIZE, 486, Short.MAX_VALUE)
                    .addComponent(pDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mVehiculoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVehiculoNuevoActionPerformed
        if(this.dialogo.mostrar()==DialogoVehiculo.ACEPTAR){
            try {
                this.tMatricula.setText(dialogo.getMatricula());
                this.tGrupo.setSelectedItem(dialogo.getGrupo());
                this.tTipo.setSelectedItem(dialogo.getTipo());
                if(dialogo.getTipo().equals("TURISMO")){
                    this.tPlazas.setValue(dialogo.getPlazas());
                }
                else{
                    this.tCapacidad.setValue(dialogo.getCapacidad());
                }
                controlador.crearVehiculo();
                this.actualizarTabla();
            } catch (MatriculaException ex) {
                mostrarMensaje("Error en la matricula");
            }
        }
    }//GEN-LAST:event_mVehiculoNuevoActionPerformed

    private void bListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarActionPerformed
        controlador.listarVehiculos();
    }//GEN-LAST:event_bListarActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        controlador.borrarVehiculo();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if(this.tMatricula.getText().trim().length()>0){
            controlador.modificarVehiculo();
        }
    }//GEN-LAST:event_bModificarActionPerformed

    private void mVehiculoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVehiculoBuscarActionPerformed
        controlador.buscarVehiculo();
    }//GEN-LAST:event_mVehiculoBuscarActionPerformed

    private void mArchivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mArchivoAbrirActionPerformed
        if(this.selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.cargarVehiculos();
        }
    }//GEN-LAST:event_mArchivoAbrirActionPerformed

    private void mArchivoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mArchivoGuardarActionPerformed
        if(this.selectorFicheros.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            controlador.guardarVehiculos();
        }
    }//GEN-LAST:event_mArchivoGuardarActionPerformed

    private void bBaratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaratoActionPerformed
        controlador.buscarVehiculoMasBarato();
    }//GEN-LAST:event_bBaratoActionPerformed

    private void bCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCaroActionPerformed
        controlador.buscarVehiculoMasCaro();
    }//GEN-LAST:event_bCaroActionPerformed
    
    public String getMatricula(){
        return this.tMatricula.getText();
    }
    
    public String getGrupo(){
        return this.tGrupo.getSelectedItem().toString();
    }
    
    public String getTipo(){
        return this.tTipo.getSelectedItem().toString();
    }
    
    public int getPlazas(){
        return (Integer)this.tPlazas.getValue();
    }
    
    public float getCapacidad(){
        return (float)this.tCapacidad.getValue();
    }
    
    public float getPrecio(){
        return (float)this.tPrecio.getValue();
    }
    
    public String getArchivo(){
        String nombre=selectorFicheros.getSelectedFile().getAbsolutePath();
        return nombre;
    }
    
    public void mostrarMatricula(String matricula){
        tMatricula.setText(matricula);
    }
    
    public void mostrarTipo(String tipo){
        tTipo.setSelectedItem(tipo);
    }
    
    public void mostrarGrupo(String grupo){
        tGrupo.setSelectedItem(grupo);
    }
    
    public void mostrarPlazas(int plazas){
        tPlazas.setValue(plazas);
    }
    
    public void mostrarCapacidad(float capacidad){
        tCapacidad.setValue(capacidad);
    }
    
    public void mostrarPrecioAlquiler(float precio){
        tPrecio.setText(String.valueOf(precio));
    }
    
    public void listarVehiculos(List<Vehiculo> listado){
        vehiculoTM.setListadoVehiculos(listado);
        tablaVehiculos.revalidate();
    }
    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public void actualizarTabla(){
        this.tablaVehiculos.revalidate();
    }
    
    public void limpiarCampos(){
        tMatricula.setText("");
        tPlazas.setValue(0);
        tPrecio.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    private DialogoVehiculo dialogo=new DialogoVehiculo(this,true);
    
    private Controlador controlador;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBarato;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bCaro;
    private javax.swing.JButton bListar;
    private javax.swing.JButton bModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lCapacidad;
    private javax.swing.JLabel lFGrupo;
    private javax.swing.JLabel lFTipo;
    private javax.swing.JLabel lGrupo;
    private javax.swing.JLabel lMatricula;
    private javax.swing.JLabel lOrden;
    private javax.swing.JLabel lPlazas;
    private javax.swing.JLabel lPrecioDia;
    private javax.swing.JLabel lTipo;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenuItem mArchivoAbrir;
    private javax.swing.JMenuItem mArchivoGuardar;
    private javax.swing.JMenu mVehiculo;
    private javax.swing.JMenuItem mVehiculoBuscar;
    private javax.swing.JMenuItem mVehiculoNuevo;
    private javax.swing.JPanel pDatos;
    private javax.swing.JPanel pListado;
    private javax.swing.JPanel pOperaciones;
    private javax.swing.JRadioButton rMatricula;
    private javax.swing.JRadioButton rPrecio;
    private javax.swing.JFileChooser selectorFicheros;
    private javax.swing.JFormattedTextField tCapacidad;
    private javax.swing.JComboBox<String> tFGrupo;
    private javax.swing.JComboBox<String> tFTipo;
    private javax.swing.JComboBox<String> tGrupo;
    private javax.swing.JTextPane tMatricula;
    private javax.swing.JSpinner tPlazas;
    private javax.swing.JFormattedTextField tPrecio;
    private javax.swing.JComboBox<String> tTipo;
    private VehiculoTableModel vehiculoTM;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables
}
